<?php

if (!defined('ABSPATH')) {
    exit;
}

class AAG_Refresher
{
    private $generator;

    public function __construct($generator)
    {
        $this->generator = $generator;
    }

    /**
     * Scan for old articles generated by the plugin.
     */
    public function scan_old_articles($days_old = 30)
    {
        global $wpdb;
        $table_name = $this->generator->table_name;

        $date_threshold = date('Y-m-d H:i:s', strtotime("-$days_old days"));

        // Find completed articles from the queue table that are older than the threshold
        $query = $wpdb->prepare(
            "SELECT q.post_id, q.title, p.post_date, p.guid 
             FROM $table_name q 
             JOIN {$wpdb->posts} p ON q.post_id = p.ID 
             WHERE q.status = 'completed' 
             AND q.post_id > 0 
             AND p.post_status = 'publish'
             AND p.post_date < %s
             ORDER BY p.post_date DESC",
            $date_threshold
        );

        return $wpdb->get_results($query);
    }

    /**
     * Get update suggestions for a specific post using Gemini.
     */
    public function get_update_suggestions($post_id)
    {
        $post = get_post($post_id);
        if (!$post) {
            return new WP_Error('post_not_found', 'Post not found.');
        }

        $api_key = get_option('aag_gemini_api_key', '');
        if (empty($api_key)) {
            return new WP_Error('no_api_key', 'Gemini API key not configured.');
        }

        $current_content = strip_tags($post->post_content);
        $current_title = $post->post_title;

        $prompt = "You are an SEO Content Strategist. Analyze the following article title and content. 
            Article Title: \"{$current_title}\"
            
            Current Content Summary: " . substr($current_content, 0, 1500) . "...
            
            I want to update this article to make it more current and improve its 'Freshness' for SEO. 
            Please provide exactly 3 specific suggestions for updates. 
            Suggestions should include:
            1. A new section to add (with a title).
            2. A data point or trend to verify/update.
            3. A structural improvement (like adding a table or list if missing).
            
            Format your response as a JSON object with a 'suggestions' array. 
            Each suggestion should have a 'title' and 'description' field.
            Example: {\"suggestions\": [{\"title\": \"Add Section: X\", \"description\": \"Detailed explanation...\"}]}";

        $response = $this->generator->call_gemini_api($prompt, $api_key);

        if (is_wp_error($response)) {
            return $response;
        }

        // Clean JSON response
        $json_text = preg_replace('/^```json\s*|\s*```$/i', '', trim($response));
        $data = json_decode($json_text, true);

        if (!isset($data['suggestions'])) {
            return new WP_Error('invalid_ai_response', 'AI did not return valid suggestions.');
        }

        return $data['suggestions'];
    }

    public function apply_suggestion($post_id, $suggestion_title, $suggestion_description)
    {
        $post = get_post($post_id);
        if (!$post) {
            return new WP_Error('invalid_post', 'Post not found.');
        }

        $api_key = get_option('aag_gemini_api_key', '');
        if (empty($api_key)) {
            return new WP_Error('no_api_key', 'Gemini API key not configured.');
        }

        $system_prompt = "You are an expert SEO content writer. Your task is to generate a new section for an existing article based on a specific update suggestion.";
        $user_prompt = "Article Title: {$post->post_title}\nExisting Content Length: " . strlen($post->post_content) . " characters.\n\nUpdate Suggestion Title: {$suggestion_title}\nUpdate Suggestion Description: {$suggestion_description}\n\nTask: Generate the FULL HTML CONTENT for this new section. It should be informative, engaging, and perfectly integrated with the original topic. Do not include the article title. Use <h2> or <h3> for subheadings if needed. Provide ONLY the HTML content. Do NOT include markdown blocks like ```html.";

        $new_section = $this->generator->call_gemini_api($user_prompt, $api_key);

        if (is_wp_error($new_section)) {
            return $new_section;
        }

        // Clean content
        $new_section = str_replace('```html', '', $new_section);
        $new_section = str_replace('```', '', $new_section);
        $new_section = trim($new_section);

        // Append to post
        $updated_content = $post->post_content . "\n\n<!-- AI Refresher Update -->\n" . $new_section;

        $update_id = wp_update_post(array(
            'ID' => $post_id,
            'post_content' => $updated_content
        ));

        if (is_wp_error($update_id)) {
            return $update_id;
        }

        return true;
    }
}
